name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm init -y
        npm install --save-dev eslint prettier

    - name: Create ESLint config
      run: |
        cat > .eslintrc.json << 'EOF'
        {
          "env": {
            "browser": true,
            "es2021": true
          },
          "extends": "eslint:recommended",
          "parserOptions": {
            "ecmaVersion": "latest",
            "sourceType": "module"
          },
          "rules": {
            "no-unused-vars": "warn",
            "no-console": "off",
            "semi": ["error", "always"],
            "quotes": ["error", "single"]
          }
        }
        EOF

    - name: Create Prettier config
      run: |
        cat > .prettierrc << 'EOF'
        {
          "semi": true,
          "trailingComma": "es5",
          "singleQuote": true,
          "printWidth": 80,
          "tabWidth": 2
        }
        EOF

    - name: Run ESLint
      run: npx eslint *.js --fix || true

    - name: Run Prettier
      run: npx prettier --check *.js *.css *.html || true

    - name: Check file sizes
      run: |
        echo "Checking file sizes..."
        find . -name "*.js" -o -name "*.css" -o -name "*.html" | while read file; do
          size=$(wc -c < "$file")
          if [ $size -gt 100000 ]; then
            echo "Warning: $file is large ($size bytes)"
          fi
        done

    - name: Security check
      run: |
        echo "Running basic security checks..."
        # Verificar por padrões inseguros
        if grep -r "eval(" *.js; then
          echo "Warning: Found eval() usage"
        fi
        if grep -r "innerHTML.*=" *.js; then
          echo "Warning: Found innerHTML usage - consider using textContent"
        fi
